 # We need sudo to install lrte packages.
sudo: true

services:
  - docker

# language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      # Package list from http://bazel.io/docs/install.html
      - openjdk-7-jdk
      - openjdk-7-source
      - zip
      - zlib1g-dev

before_install:
  - docker pull ubuntu:14.04
install:
  - ./install-bazel.sh
  - ./install-lrte.sh

script:
  - docker info
  - make all

notifications:
  email: false
